# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from pytube import YouTube




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(689, 485)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        #video bilgileri yazı kısmı ekrana yazdırılacak
        
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(150, 180, 401, 192))
        self.textBrowser.setObjectName("textBrowser")
        

        #indir butonu 
        self.indir = QtWidgets.QPushButton(self.centralwidget)
        self.indir.setGeometry(QtCore.QRect(280, 420, 151, 51))
        self.indir.setObjectName("indir")
        self.indir.clicked.connect(self.indir_clicked)  # Connect the clicked signal to a function

        #link verisi kısmı buradan link verisi alınacak
        self.linkyeri = QtWidgets.QLineEdit(self.centralwidget)
        self.linkyeri.setGeometry(QtCore.QRect(170, 60, 381, 20))
        self.linkyeri.setObjectName("linkyeri")

        #burası yazı bir işe yaramıyor
        self.linkyazi = QtWidgets.QLabel(self.centralwidget)
        self.linkyazi.setGeometry(QtCore.QRect(270, 20, 161, 31))
        self.linkyazi.setObjectName("linkyazi")

        #burası video bilgi yazısı | bir işe yaramıyor
        self.videobilgiyazi = QtWidgets.QLabel(self.centralwidget)
        self.videobilgiyazi.setGeometry(QtCore.QRect(280, 150, 151, 31))
        self.videobilgiyazi.setObjectName("videobilgiyazi")

        #videoyu önizlemeyi sağlar
        self.onizle = QtWidgets.QPushButton(self.centralwidget)
        self.onizle.setGeometry(QtCore.QRect(280, 90, 151, 51))
        self.onizle.setObjectName("onizle")
        self.onizle.clicked.connect(self.onizleclicked)
        
        #nereye kaydediceğini seçme işareti
        self.konumolsunmu = QtWidgets.QCheckBox(self.centralwidget)
        self.konumolsunmu.setGeometry(QtCore.QRect(280, 380, 151, 21))
        self.konumolsunmu.setObjectName("konumolsunmu")
        
        
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def indir_clicked(self):
        
        if self.konumolsunmu.isChecked():
            file_dialog = QtWidgets.QFileDialog()
        
            file_path = file_dialog.getExistingDirectory(None)

            print("Selected File Path: ", file_path)

            link = self.linkyeri.text()
        print("Link: ", link)
        
        youtubeObject = YouTube(link)
        youtubeObject = youtubeObject.streams.get_highest_resolution( )
        
        try:
            
            youtubeObject.download(output_path = file_path)
            print("Video başarıyla indirildi")    
            # QTextBrowser'a "Merhaba" yazdırma







        except:
            print("bir sorun oldu yeniden dene")
        

    def onizleclicked(self):
        print("devam edecek")
        
        
        link = self.linkyeri.text()
        youtubeObject = YouTube(link)
        caption = youtubeObject.captions.get_by_language_code('en')

        print(caption)
        #self.textBrowser.setText(caption)
        

    
    
    



    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.indir.setText(_translate("MainWindow", "İNDİR"))
        self.linkyazi.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#aa0000;\">Video Linkini Girin</span></p></body></html>"))
        self.videobilgiyazi.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#aa0000;\">Video Bilgileri</span></p></body></html>"))
        self.onizle.setText(_translate("MainWindow", "VİDEOYU ÖNİZLE"))
        self.konumolsunmu.setText(_translate("MainWindow", "nereye kaydedeceğini seç"))

    
    





if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


