# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(689, 485)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.indir = QtWidgets.QPushButton(self.centralwidget)
        self.indir.setGeometry(QtCore.QRect(280, 420, 151, 51))
        self.indir.setObjectName("indir")
        self.linkyeri = QtWidgets.QLineEdit(self.centralwidget)
        self.linkyeri.setGeometry(QtCore.QRect(170, 60, 381, 20))
        self.linkyeri.setObjectName("linkyeri")
        self.linkyazi = QtWidgets.QLabel(self.centralwidget)
        self.linkyazi.setGeometry(QtCore.QRect(270, 20, 161, 31))
        self.linkyazi.setObjectName("linkyazi")
        self.videobilgiyazi = QtWidgets.QLabel(self.centralwidget)
        self.videobilgiyazi.setGeometry(QtCore.QRect(280, 150, 151, 31))
        self.videobilgiyazi.setObjectName("videobilgiyazi")
        self.dosyakonumu = QtWidgets.QPushButton(self.centralwidget)
        self.dosyakonumu.setGeometry(QtCore.QRect(280, 90, 151, 51))
        self.dosyakonumu.setObjectName("dosyakonumu")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(150, 180, 401, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.konumolsunmu = QtWidgets.QCheckBox(self.centralwidget)
        self.konumolsunmu.setGeometry(QtCore.QRect(280, 380, 151, 21))
        self.konumolsunmu.setObjectName("konumolsunmu")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.indir.setText(_translate("MainWindow", "İNDİR"))
        self.linkyazi.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#aa0000;\">Video Linkini Girin</span></p></body></html>"))
        self.videobilgiyazi.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#aa0000;\">Video Bilgileri</span></p></body></html>"))
        self.dosyakonumu.setText(_translate("MainWindow", "DOSYA KONUMUNU SEÇ"))
        self.konumolsunmu.setText(_translate("MainWindow", "nereye kaydedeceğini seç"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
